<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE profesiones [
    <!ELEMENT profesiones (profesion*)>
    <!ELEMENT profesion (informatico | docente | quimico)>
    <!ELEMENT informatico (#PCDATA)>
    <!ELEMENT docente (#PCDATA)>
    <!ATTLIST docente especialidad CDATA #IMPLIED>
    <!ELEMENT quimico (#PCDATA)>
]>

<profesiones>
    <profesion>
        <informatico></informatico>
    </profesion>

    <profesion>
        <docente especialidad="programacion"></docente>
    </profesion>

    <profesion>
        <quimico></quimico>
    </profesion>
</profesiones>