<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musica [
    <!ELEMENT musica (disco*)>
    <!ELEMENT disco (titulo, a単o, canciones*)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT a単o (#PCDATA)>
    <!ELEMENT canciones ANY>
]>
<musica>
    <disco>
        <titulo></titulo>
        <a単o></a単o>
        <canciones></canciones>
        <canciones></canciones>
    </disco>
</musica>