
<!-- Ejercicio 1 -->

<?xml-model href="file.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!DOCTYPE aeropuerto [
    <!ELEMENT aeropuerto (nombre,vuelo+, fecha)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT vuelo (diario?, origen, destino, hora_salida, hora_llegada)>
        <!ATTLIST vuelo codigo ID #REQUIRED>
        <!ATTLIST vuelo estado (C|E|R) "E">

    <!ELEMENT diario EMPTY>
    <!ELEMENT origen (#PCDATA)>
    <!ELEMENT destino (#PCDATA)>
    <!ELEMENT hora_salida (#PCDATA)>
    <!ELEMENT hora_llegada (#PCDATA)>
    

    
]>

<aeropuerto>
<nombre>Barajas</nombre>
    <vuelo codigo="V10" estado="R">
        <diario />
        <origen>Alicante</origen>
        <destino>Madrid</destino>
        <hora_salida>9:30</hora_salida>
        <hora_llegada>10:30</hora_llegada>
    </vuelo>

        <vuelo codigo="V11" estado="C">
        <origen>Alicante</origen>
        <destino>Barcelona</destino>
        <hora_salida>10:15</hora_salida>
        <hora_llegada>12:15</hora_llegada>
    </vuelo>
<fecha>10/02/2025</fecha>
</aeropuerto>
